### ISSUE TITLE
Nested Groups don't work

### ISSUE THREAD

**Issue by lordworldbog** [lavary/laravel-menu#91]
I'm trying to use this example in middleware

    Menu::make('MyNavBar', function($menu){
            $menu->group(array('prefix' => 'pages', 'data-info' => 'test'), function($m){

                $m->add('About', 'about');

                $m->group(array('prefix' => 'about', 'data-role' => 'navigation'), function($a){

                    $a->add('Who we are', 'who-we-are?');
                    $a->add('What we do?', 'what-we-do');
                    $a->add('Our Goals', 'our-goals');
                });
            });
    });

And this line in blade
`{!! Menu::get('MyNavBar')->asUl( ) !!}`

That's what i get as a result

    <ul>
       <li><a href="http://****/pages/about">About</a></li>
       <li><a href="http://****/pages/about/who-we-are?">Who we are</a></li>
       <li><a href="http://****/pages/about/what-we-do">What we do?</a></li>
       <li><a href="http://****/pages/about/our-goals">Our Goals</a></li>
    </ul>

Instead of 

    <ul>
        ...
        <li data-info="test">
            <a href="http://yourdomain.com/pages/about">About</a>
            <ul>
                <li data-info="test" data-role="navigation"><a href="http://yourdomain.com/pages/about/who-we-are"></a></li>
                <li data-info="test" data-role="navigation"><a href="http://yourdomain.com/pages/about/what-we-do"></a></li>
                <li data-info="test" data-role="navigation"><a href="http://yourdomain.com/pages/about/our-goals"></a></li>
            </ul>
        </li>
    </ul>

**Comment by ittikorns** [comment]
+1

**Comment by rafaelbazanella** [comment]
+2 :(

**Comment by lavary** [comment]
The issue has been fixed in the latest release. Please update the package.

**Comment by lavary** [comment]
Closing the issue, feel free to reopen if you face a problem.

**Comment by calinblaga** [comment]
Nested groups still not rendering as 
`<ul>
						<li>
							<ul>
								<li></li>
								<li></li>
								<li></li>
							</ul>
						</li>
					</ul>`
